include:
  - remote: "https://gitlab.com/Kozea/ci-master/raw/master/.gitlab-ci-master.yml"

.artifacts: &artifacts_install
  artifacts:
    paths:
      - node_modules/
      - .venv/

.artifacts: &artifacts_build
  artifacts:
    paths:
      - lib/frontend/static/
      - node_modules/
      - .venv/

install:
  <<: *artifacts_install

build:
  <<: *artifacts_build
